### ISSUE TITLE
Could not pass chunkunloadevent to

### ISSUE THREAD

**Issue by RustyDagger** [Krakenied/BlockTracker#1]
Running Paper version 1.21-46-master@2fa5e0e and the latest blocktracker.

spams so much console is unreadable. and shutdown oh boy nope.

`- [Wed 22:42:02 ERROR Minecraft] Could not pass event ChunkUnloadEvent to BlockTracker v1.0.6
java.lang.StackOverflowError
    at java.base/java.lang.StringUTF16.putCharsSB(StringUTF16.java:1342)
    at java.base/java.lang.AbstractStringBuilder.appendChars(AbstractStringBuilder.java:1798)
    at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:688)
    at java.base/java.lang.StringBuilder.append(StringBuilder.java:218)
    at org.apache.logging.log4j.message.ParameterFormatter.formatMessageContainingNoEscapes(ParameterFormatter.java:259)
    at org.apache.logging.log4j.message.ParameterFormatter.formatMessage(ParameterFormatter.java:243)
    at org.apache.logging.log4j.message.ParameterizedMessage.formatTo(ParameterizedMessage.java:266)
    at org.apache.logging.log4j.message.ParameterizedMessage.getFormattedMessage(ParameterizedMessage.java:248)
    at org.apache.logging.log4j.message.ParameterizedNoReferenceMessageFactory.newMessage(ParameterizedNoReferenceMessageFactory.java:106)
    at org.apache.logging.log4j.message.AbstractMessageFactory.newMessage(AbstractMessageFactory.java:103)
    at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2713)
    at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:2487)
    at org.apache.logging.log4j.spi.AbstractLogger.warn(AbstractLogger.java:3701)
    at org.apache.logging.log4j.spi.AbstractLogger.handleLogMessageException(AbstractLogger.java:2954)
    at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2936)
    at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2886)
    at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2868)
    at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2647)
    at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:2594)
    at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:835)`

**Comment by Krakenied** [comment]
Confirmed incompatibility between BlockTracker and Paper 1.21+

Tracked in https://github.com/PaperMC/Paper/issues/10900
